pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        mavenLocal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
}

include ':BlinkReceiptEarnings'
include ':BlinkReceiptImap'
include ':BlinkReceiptOutlook'
include ':BlinkReceiptStaticScan'
include ':ActualActivation'
include ':BlinkReceiptCustomScan'
include ':BlinkReceiptSurveys'
include ':BlinkReceiptAccountLinking'
include ':BlinkReceiptScanPdf'
