plugins {
    alias(libs.plugins.android.application)
}

def versionMajor = libs.versions.versionMajor.get().toInteger()
def versionMinor = libs.versions.versionMinor.get().toInteger()
def versionPatch = libs.versions.versionPatch.get().toInteger()

android {
    compileSdkVersion libs.versions.compileSdk.get().toInteger()
    buildToolsVersion libs.versions.buildTools.get()

    defaultConfig {
        applicationId "com.blinkreceipt.linking"
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.targetSdk.get().toInteger()

        versionCode versionMajor * 10000 + versionMinor * 1000 + versionPatch * 100
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }

    signingConfigs {
        release {
            storeFile file("../blink-receipt-demos.jsk")
            storePassword providers.gradleProperty('demoStorePassword').get()
            keyAlias providers.gradleProperty('demoKeyAlias').get()
            keyPassword providers.gradleProperty('demoKeyPassword').get()
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        resources {
            excludes += [
                    'META-INF/NOTICE.md',
                    'META-INF/LICENSE.md',
                    'META-INF/ASL2.0',
                    'META-INF/AL2.0',
                    'META-INF/LGPL2.1',
                    'META-INF/licenses/ASM',
                    'META-INF/DEPENDENCIES',
            ]
        }
    }

    namespace 'com.blinkreceipt.linking'

}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation libs.androidx.constraintlayout
    implementation libs.material
    implementation libs.play.services.tasks

    implementation libs.androidx.core.ktx

    implementation platform(libs.blinkreceipt.bom)
    implementation libs.blinkreceipt.account.linking

    testImplementation libs.junit

    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}
